
<?php //echo $block->getpath();  ?>
<!-- <div class="importForm"> -->
<form method="get" class="importForm" action=<?php echo $this->getUrl('*/*/')?> >
    <!-- <input type="submit" id="read" name="read"  value="Read Last Importing Log" class="importButton importButton3" onclick="lastLog()"/> -->
    <input  type="submit" id="read" name="read"  value="Read Last Importing Log" class="importButton importButton3" />
    <input  type="submit" name="run"   value="Run New Importing"  class="importButton importButton1" />
</form>
<?php
  
  function runMyFunction() {
    //$p = $block->getContents();
    //echo $p;
    echo 'I just ran a php function';
  }

  if (isset($_GET['hello'])) {
    runMyFunction();
  }
  //echo $this->getUrl('*/*/').'?hello=true';
  //echo $block->getContents();
?>

<!-- Hello there!
<a href=<?php //echo $this->getUrl('*/*/').'?hello=true' ?> >Run PHP Function</a>
<div id="log"><span></span></div>
<div id="ddd"><span></span></div> -->
<script>
// document.getElementById('read').onclick = function()
// {
//   document.getElementById("log").innerHTML = "<?php //echo $block->getContents();  ?>"
// };
// function lastLog(){
//   document.getElementById("log").innerHTML = "<?php //echo $block->getContents();  ?>";
// }
// function importManually(){
//   document.getElementById("ddd").innerHTML = "<?php //echo $block->importingManually();  ?>";
// }
</script>

    <div>
        <span><?php if(isset($_GET['read'])){ echo $block->getContents();} ?></span>   
        <span><?php if(isset($_POST['read'])){ echo $block->getContents();} ?></span>   
    </div>
    <div>
<span><?php if(isset($_GET['run'])){ $block->importingManually();/*echo $block->getContents();*/} ?></span>   
<span><?php if(isset($_POST['run'])){ $block->importingManually();/*echo $block->getContents();*/} ?></span>   
    </div>

<style>
.importForm {
    display:flex;
    justify-content: center;
}
.importButton {
  background-color: #4CAF50; /* Green */
  border: none;
  color: white;
  padding: 16px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  -webkit-transition-duration: 0.4s; /* Safari */
  transition-duration: 0.4s;
  cursor: pointer;
}

.importButton1 {
  background-color: white; 
  color: black; 
  border: 2px solid #4CAF50;
}

.importButton1:hover {
  background-color: #4CAF50;
  color: white;
}

.importButton3 {
  background-color: white; 
  color: black; 
  border: 2px solid #f44336;
}

.importButton3:hover {
  background-color: #f44336;
  color: white;
}
table {
  width:100%;
}
table, th {
  border: 1px solid #8a837f;
  border-collapse: collapse;
}
td {
  border-left-width: 0.1rem;
    border-left-style: dashed;
    border-left-color: rgb(214, 214, 214);
    border-right-width: 0.1rem;
    border-right-style: dashed;
    border-right-color: rgb(214, 214, 214);
    border-collapse: collapse;
}
th, td {
  padding: 15px;
  text-align: center;
}
table#titles tr:nth-child(even) {
  background-color: #e5e5e5;
}
table#titles tr:nth-child(odd) {
 background-color: #fff;
}
table#titles th {
  background-color: #514943;
  color: white;
}
@media only screen and (min-width:715px){
  thead th { 
    position: sticky;
    top: 76px;
  }
}
@media only screen and (max-width:705px) and (min-width:567px){
  thead th { 
    position: sticky;
    top: 116px ;
  }
}
</style>
